### ISSUE TITLE
How to compile under Ubuntu?

### ISSUE THREAD

**Issue by nshram** [thomas-maeder/popeye#199]
Hello!
Could somebody point me to ways to compile the sources under Ubuntu Linux?
I keep trying now and then but never succeeded. One or the other error message appears.
This time:
- I copied makefile.unx to makefile
- entered command make makefile
- got this message:

makefile:339: target `output/latex/nesteddepend' given more than once in the same rule.
make: Nothing to be done for `makefile'.

**Comment by thomas-maeder** [comment]
> makefile:339: target output/latex/nesteddepend' given more than once in the same rule.

This is just a warning. I have not come around getting rid of it yet.

> make: Nothing to be done formakefile'.

That's the useful hint:
% make makefile
attempts to make the makefile, which is not necessary since it already exists and doesn't have any dependencies.

To make *according to* makefile, do
% make -f makefile
or just
% make

To speed up things, you might try
% make -j

**Comment by nshram** [comment]
Thanks, Thomas!
makefile -j worked.
But... I'm not able to locate the final executable popeye file! Where do I look for it? In the same directory as the makefile?

**Comment by thomas-maeder** [comment]
The executable file is called py
