### ISSUE TITLE
MaxSolutions sometimes works not correctly

### ISSUE THREAD

**Issue by osick** [thomas-maeder/popeye#319]
In some cases the output number of solutions is larger than maxsolution. 
Take for example the (random) problem

_BeginProblem
Stipulation hs#6
Option MaxSolutions 11
Condition AntiCirce Calvet Maximummer NoCapture Sentinelles 
Pieces neutral  Pa5f7 Kd8
EndProblem_

The number of output solutions is  **12**, tis is larger than the "maxsolution given in the input.
If we replace the "maxsol 11" with "maxsol 10" it works well and returns 10 solutions.

This was observed with version 4.83 on windows, I've not checked it with oether constellations.

I've observed the beaviour occasionaly with some other (and less weird) problems and older version of popeye.

**Comment by thomas-maeder** [comment]
Your observation is wrong. There are only 11 solutions. But the 11th solution:

  1.nPf7-f8=nS nSf8-d7   2.nSd7-b6[+wPd7] nSb6-c4[+bPb6]   3.nKd8-c7 nSc4-b2[+bPc4]   4.nSb2-a4[+wPb2] nSa4-c5[+bPa4]   5.nKc7-c6[+wPc7] nSc5-a6[+bPc5]   6.nKc6-b5[+wPc6] nSa6-b4[+bPa6] #
  1.nPf7-f8=nS nSf8-d7   2.nSd7-b6[+wPd7] nSb6-c4[+bPb6]   3.nKd8-c7 nSc4-b2[+bPc4]   4.nSb2-a4[+wPb2] nSa4-c5[+bPa4]   5.nKc7-c6[+wPc7] nSc5-a6[+bPc5]   6.nKc6-b5[+wPc6] nSa6-b8[+bPa6] #

has two **variations**.

Remember that we are in "selfmate mode" after White's last move; different black moves are not solutions, but variations.

**Comment by thomas-maeder** [comment]
Unfortunately, this doesn't mean that Popeye's behavior is correct. Because there is another solution with 2 variations, so we only get 10 solutions despite having asked for 11.

But taking into consideration that
* counting the number of solutions is a bit tricky in stipulations such as hs#, and
* the intent of option maxsolutions being the reduction of the number of printed solutions to a manageable set rather than an exact number

, I am closing this issue.
